Validateform branch
luisrpavanelli/Portfolio pull request #15
Opened 2023-05-18 17:28 UTC by luisrpavanelli

2023-05-18 20:07 UTC, Munsa1 requested changes
Hi @luisrpavanelli, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Added More Than One Validation Check :heavy_check_mark:  
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 20:07 UTC, Munsa1 commented on script.js
> +};
- [ ] At the moment, when the user enters an Email Address with a capital letter, the form submits successfully. Kindly fix this. You could consider adding this function to the submit button instead. You could also rearrange the expression to first check if the email is in lowercase, then have an else statement for if it is not. e.g.

```
if (email === email.toLowerCase()){
code here
}
else{
code here
}

2023-05-18 20:07 UTC, Munsa1 commented on script.js
> +  } else if (sendingEmail === '') {
- [ ] Since I am unable to to see the message now, kindly make sure the error message shows up close to the `submit` button or the `input fields`. (i.e error message can show up around the input fields or just around the submit button)

2023-05-19 00:33 UTC, luisrpavanelli commented
Hi, Optional suggestions are done!

2023-05-19 00:40 UTC, Davidosky007 approved these changes
Hi @luisrpavanelli 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Form validation added properly 👍 
* Good looking readme 👍 
* Well written PR 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 00:55 UTC, merged